[workspace]
members = ["assembly", "prover"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0"
binius_core = { git = "https://github.com/IrreducibleOSS/binius.git" }
binius_field = { git = "https://github.com/IrreducibleOSS/binius.git" }
binius_utils = { git = "https://github.com/IrreducibleOSS/binius.git" }
binius_m3 = { git = "https://github.com/IrreducibleOSS/binius.git" }
binius_hash = { git = "https://github.com/IrreducibleOSS/binius.git" }
binius_hal = { git = "https://github.com/IrreducibleOSS/binius.git" }
