[workspace]
members = ["assembly", "prover", "verifier"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["The PetraVM Developers"]
description = "PetraVM: a zkVM optimized for efficient recursive composition backed by the Binius proving system."
license = "Apache-2.0"
repository = "https://github.com/PetraProver/PetraVM"
homepage = "https://github.com/PetraProver/PetraVM"
documentation = "https://docs.rs/petravm"
readme = "README.md"
keywords = ["zkvm", "zero-knowledge", "binius", "rust", "snark"]
categories = ["cryptography", "compilers", "wasm"]

[workspace.dependencies]
ahash = "0.8.12"
anyhow = "1.0"
tracing = "0.1.41"
tracing-forest = { version = "0.1.6", features = ["ansi"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Binius dependencies
binius_core = { path = "../binius/crates/core" }
binius_field = { path = "../binius/crates/field" }
binius_hal = { path = "../binius/crates/hal" }
binius_hash = { path = "../binius/crates/hash" }
binius_m3 = { path = "../binius/crates/m3" }
binius_utils = { path = "../binius/crates/utils" }
# binius_core = { git = "https://github.com/IrreducibleOSS/binius.git" }
# binius_field = { git = "https://github.com/IrreducibleOSS/binius.git" }
# binius_hal = { git = "https://github.com/IrreducibleOSS/binius.git" }
# binius_hash = { git = "https://github.com/IrreducibleOSS/binius.git" }
# binius_m3 = { git = "https://github.com/IrreducibleOSS/binius.git" }
# binius_utils = { git = "https://github.com/IrreducibleOSS/binius.git" }

[profile.release]
lto = "fat"
