[package]
name = "zcrayvm-prover"
version.workspace = true
edition.workspace = true
authors = ["zCray Team"]

[dependencies]
anyhow.workspace = true
bumpalo = { version = "3.16.0", features = ["collections"] }
bytemuck = { version = "1.18.0", features = ["derive", "min_const_generics"] }
clap = { version = "4.5.20", features = ["derive"] }
env_logger = "0.11.7"
log = "0.4"
paste = "1.0.15"
thiserror = "2.0.11"
zcrayvm-assembly = { path = "../assembly" }

# Binius dependencies
binius_core.workspace = true
binius_field.workspace = true
binius_hal.workspace = true
binius_hash.workspace = true
binius_m3.workspace = true

[dev-dependencies]
binius_m3 = { workspace = true, features = ["test_utils"] }
proptest = "1.4.0"
rand = { version = "0.9.1", features = ["std"] }
zcrayvm-assembly = { path = "../assembly" }
criterion = "0.5.1"

# Explicitly define the benchmark target
[[bench]]
name = "shift"
harness = false # Criterion provides its own harness
