---  # Rust lint related checks

name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - run: cargo clippy --all-targets -- -D warnings
  udeps:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps
      - run: cargo udeps --quiet --all-targets --workspace
  rustdoc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - run: |-
          RUSTDOCFLAGS='-D warnings \
            -A rustdoc::private_intra_doc_links \
            -A rustdoc::broken-intra-doc-links' \
          cargo doc --all --no-deps

  cargo-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - run: cargo fmt --check
  taplo-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli
      - run: taplo fmt --check
  outdated:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-outdated
      - run: cargo outdated --workspace --aggressive
